### ISSUE TITLE
日本語とアルファベットが混合した場合のフォーマットについて

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/vuejs.org#1]
翻訳していると、文の途中にアルファベット(例えば、`HTML`とか`CSS`などの特定の用語など)が入ってくると思いますが、そのアルファベットの前後に半角スペースを入れるか入れないか、迷っているんですが、どうしましょう？
というより、フォーマットを統一したいです。
- 半角スペース入れた場合の例

```
これは HTML と CSS が必要です。
```
- 半角スペースを入れない場合の例

```
これはHTMLとCSSが必要です。
```

参考
https://developer.mozilla.org/ja/docs/Web/JavaScript

個人的には、半角スペースを入れたほうが読みやすいと思っているので、こちらにしたいです。

**Comment by hashrock** [comment]
半角スペース入れで問題ないと思います！

**Comment by kazupon** [comment]
@hashrock 
回答、ありがとうございます！

/cc all
特に異論がなければ、これで行きたいと思います！

**Comment by tejitak** [comment]
了解です
