### ISSUE TITLE
vuejs#77の取り込み

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/vuejs.org#39]
https://github.com/vuejs/vuejs.org/pull/77 の取り込み

**Comment by yyx990803** [comment]
Just a note I've edited it quite extensively in a new commit: https://github.com/vuejs/vuejs.org/commit/0e6ee53a928eed880e7055a59c7fcb0222ded335

**Comment by kazupon** [comment]
#42 で最新内容盛り込み済み
