### ISSUE TITLE
v-attrの0.12.8での追加機能の訳について

### ISSUE THREAD

**Issue by chi-bd** [vuejs-jp/vuejs.org#51]
ディレクティブv-attrの0.12.8 以降での追加機能について、

> 例えば、<input value="{{val}}"> は属性を更新するだけではなく、value プロパティを設定しません。

と訳されていますが、原文は、

> For example, <input value="{{val}}"> will not only update the attribute, but also set the value property.

という"not only A, but also B"構文ですから、AもBも否定形ではなく肯定形で訳すのが正しいのではないでしょうか？
（「value プロパティを設定しません」→「value プロパティも設定します」）

**Comment by kazupon** [comment]
ご指摘ありがとうございます！ 
確かにそうですね。こちら修正しておきますね！ :smile:

**Comment by kazupon** [comment]
修正してサイトの方に反映させました。
ご確認くださいませ。
http://jp.vuejs.org/api/directives.html#v-attr

**Comment by chi-bd** [comment]
修正を確認しました。早急な対応ありがとうございます
