### ISSUE TITLE
0.12.12 までの追加翻訳

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/vuejs.org#59]
## 追加翻訳内容

以下の 本家 vuejs/vuejs.org の commit 内容の翻訳
- [x] de06e322c776c763854ccc782c56b694e3d2908f
- [x] de23a51dc963930501609ba3ba85b3b7eec56a74
- [x] fcc8b3e3dd19077b3910296829ec664fbf03bfe9
- [x] 2b3e0ad11bc2b711a599941155410e7b2aa5c292
- [x] 2c88b710140fc9bf40640714aa2cdf706dd5a0b0
- [x] a52268da4d5a13d2e4977911dda50f084d35541a
- [x] fc2cf43de9d25866dda58867d7a0dd4152e26936
- [x] a8842c768b706ed2cfab7ae59954df2510e8157f
- [x] faa2cd18f1e234b349529821ffbc48edce2e1275
- [x] 7708f82d480d2bb6d5b960239b33a92975eba538
- [x] c4bcca27930090d85815f9ae54c9d5849cb9520b (追加: 2015-09-01)
- [x] 569a1c1611c521a9550ad9e55901e1e1d0e52c8a (追加: 2015-09-01)
## 翻訳作業のやり方
1. 上記 commit を上から順に翻訳する
2. `make update` で vue 関連のファイルを更新し、それらを commit
3. Pull Request
## 翻訳やりたい方

コメントで一言表明してください

**Comment by mono0x** [comment]
お、ちょっとやってみたいです。

**Comment by kazupon** [comment]
お、ではよろしくお願いします。👍🏼

**Comment by kazupon** [comment]
https://github.com/vuejs-jp/vuejs.org/pull/62
