### ISSUE TITLE
各記事タイトルの訳

### ISSUE THREAD

**Issue by hashrock** [vuejs-jp/vuejs.org#7]
例えば、下記文章のように、記事末尾から他の記事にリンクしていることがあります。

> Now that you know what directives and filters are, let's get our hands dirty and try to [display a list of items](/guide/list.html).

記事間に表記ゆれが発生しそうです。
先に記事タイトルのみ訳しておいてもいいかもしれません。
（あとで直せばいいような気もしますが）

**Comment by kazupon** [comment]
oops ...
これも、昨日のMTGのときに、議論し忘れてました。。。

そうですね。
とりあえず、訳がひと通り終わってから、こちらで直しますね。
