### ISSUE TITLE
Hosting 0.12 docs after 1.0 release

### ISSUE THREAD

**Issue by yyx990803** [vuejs-jp/vuejs.org#75]
The English version will be hosted at `012.vuejs.org`. For Japanese version, please create a repo named `012-jp.vuejs.org` and host the old versions there :)

**Comment by kazupon** [comment]
All right! :)

**Comment by kazupon** [comment]
Done!
Please check :)
http://012-jp.vuejs.org

**Comment by yyx990803** [comment]
Cool! One small thing: the home page github star button needs to change its url from yyx990803/vue to vuejs/vue

**Comment by kazupon** [comment]
Thanks for your checking!!
I fixed tiny mistake. :)
