### ISSUE TITLE
訳注

### ISSUE THREAD

**Issue by hashrock** [vuejs-jp/vuejs.org#8]
訳注とかも入れていった方がいいのでしょうか？

例えば、ディレクティブの説明の中に、特に説明なくMustacheとか出てくるんですが、
気づいた時に説明を足していくのもいいのかな、と思いました。

**Comment by kazupon** [comment]
ごめんさない。
昨日のMTGのときに、議論し忘れてました。。。

註釈あると確かにいいかもしれないですね。
ホントに初めての方もいるかもしれないので。

ただ、個人的には、説明出来るページがあれば、そこにリンクはるのも悪くないのかなあと思ったりもしています。

**Comment by hashrock** [comment]
対象読者層を考えると、Mustache等は知ってて当然のような気もしてきました。
わかりづらい部分は、PR上で議論できればそれで良さそうなので、本件はCloseします。
