### ISSUE TITLE
About repository hosting on vuejs orgnaization

### ISSUE THREAD

**Issue by kazupon** [vuejs-jp/vuejs.org#80]
Hi @yyx990803 !!

As for the cn.vuejs.org translation repository was recently hosted on vuejs orgnazation, we think that want to host the following our repositories.
- vuejs-jp/vuejs.org
- vuejs-jp/012-jp.vuejs.org

In vuejs organzation, you can  allow to me team creating and repository creating permission now.
May I moved the vuejs.org translation repository to the vuejs orgnaization ?

PS: 
I hope that you can allow to other translation users (vuejs-ru, etc) by open source governance like nodejs(iojs). :wink:

**Comment by yyx990803** [comment]
Yes, I'd love to do that!

**Comment by yyx990803** [comment]
I think the best way to do that is to transfer the repo directly to the vuejs organization. To do that I will need admin rights to the vuejs-jp organization. Once transferred I will setup a vuejs-jp team and invite everyone here.

**Comment by kazupon** [comment]
Thanks!

I gave you the admin permission on vuejs-jp organization!

**Comment by yyx990803** [comment]
Ah well, since jp.vuejs.org is a fork of the original vuejs.org, GitHub doesn't allow it to be transferred into the same organization. I have created a fresh repo at https://github.com/vuejs/jp.vuejs.org where you now have admin rights to. You are also the maintainer of the `vuejs-jp` team which should allow you to add team members.

**Comment by yyx990803** [comment]
Oh, it seems they must be invited into the organization first. Just let me know who I should invite.

**Comment by kazupon** [comment]
Thank!
I see :)

**Comment by kazupon** [comment]
I moved vuejs-jp/jp.vuejs.org to vuejs/jp.vuejs.org

At the end, Can you please set the DNS (cname) as following ?
- current (guess)
  http://vuejs-jp.github.io/vuejs.org/
- new
  http://vuejs.github.io/jp.vuejs.org/

**Comment by yyx990803** [comment]
I have updated the DNS. It should take effect any time.

**Comment by kazupon** [comment]
Thanks!!
