### ISSUE TITLE
Archiveした方がいいのでは

### ISSUE THREAD

**Issue by monmonmon** [vuejs-jp/vuejs.org#81]
日本語訳のリポジトリが本家とこちらの2つあることでちょっと混乱してしまいました。
READMEに本家に移行したと書いてありますが、リポジトリをArchiveしてしまった方がより明示的になると思うのですがいかがでしょうか？

**Comment by kazupon** [comment]
フィードバックありがとうございます。
Archive してしまいところですが、この repositoryは現在 Vue.js 1.0、0.12 といった Vue 2.x 以前のバージョンをホストするドキュメントなので、残しています。

**Comment by kazupon** [comment]
ああ、ごめんなさい。
0.12 は別でしたね。
1.0 系でした。

**Comment by monmonmon** [comment]
ご回答ありがとうございます。承知しました。
